### ISSUE TITLE
Latest docker version 

### ISSUE THREAD

**Issue by mariushosting** [machengim/oasis#12]
Latest docker version point to version 0.2 instead of 0.2.1

**Comment by machengim** [comment]
Thanks for pointing it out. It's updated.

**Comment by mariushosting** [comment]
Thank you now is correctly point to the new version! Awesome work! Hope we can add search bar and the possibility to change some text inside some text file then save it.

**Comment by machengim** [comment]
Your kindness is really appreciated, but currently there are no support options. The search functionality should come in next one or two release, while text editor may take longer. Thanks for your patience.
