### ISSUE TITLE
Password length should be the same

### ISSUE THREAD

**Issue by mprajescu** [machengim/oasis#13]
Just launch Oasis executable on windows. 
Setup the config through gui. 
Entered username "admin" and password "1234". 
Select storage, click OK. 

Cannot login when the configuration is complete. 
Minimum password requirement is not implemented in the web setup.

**Comment by machengim** [comment]
This is interesting. I just tested it on Windows with Chrome, Edge and Firefox, but cannot reproduce this issue. As the minimum password length is 6, the form refused to submit when only 4 digits are input. Could you please check if the setup is done? If the setup was successful, you should get a 403 forbidden page when trying to access `http://ip:8000/setup`. If you see this 403 page, and you believe you have input 4 digits as the password, please tell me which browser you're using.
