### ISSUE TITLE
CloudDrive 磁盘无法被找到

### ISSUE THREAD

**Issue by yioMe** [machengim/oasis#16]
hi，我非常喜欢oasis这个项目，当我在使用oasis时，无法找到CloudDrive挂载到本地的阿里云盘磁盘，可以打算兼容一下吗？

**Comment by machengim** [comment]
感谢支持。没有用过阿里云盘，不知道具体它是如何挂载的，文件是保存在本地还是云端？云端访问暂时没有计划。

**Comment by yioMe** [comment]
Hello, I have received your message, I will be back to see you reply as soon as possible.
  您好，您的邮件我已收到，我将在看到后，尽快给您回复。
