### ISSUE TITLE
Drag'n drop ?

### ISSUE THREAD

**Issue by Fabeuss** [machengim/oasis#19]
First of all a big thanks for Oasis, I really love it...

Would it be possible to add the drag'n drop to upload files ?

Thanks

**Comment by machengim** [comment]
Thanks for your support. DnD for moving files is considered, but not sure about using it for upload yet. Will let you know if it's added to the roadmap in the future.

**Comment by Fabeuss** [comment]
ok thanks for the reply 👍🏼

**Comment by machengim** [comment]
Just FYI, drag and drop upload is supported in v0.2.5, please check it.

**Comment by Fabeuss** [comment]
Hi, yeah just saw that, thank you very much for your work, it works well 👍
