### ISSUE TITLE
[feature] Open HTML files and the permanent files link

### ISSUE THREAD

**Issue by MisteryMonster** [machengim/oasis#22]
I hope the static HTML files I served can preview directly ( of course with resource linked )! Currently it just preview as a text file, or using the `/api/file` to get the file (but all the `/` are rewrite to `%2F` so all the resources get the 404 error ( maybe is a bug? ). Share link should add an API direct point to the file ( Considering there is a temporary link, maybe giving an permanent URL parameters like `/api/file/root/folders/index.html?t=never-expire-token` is a good idea? )

**Comment by machengim** [comment]
I don't think we're going to support static website hosting as it's a quite different area, better to keep the app minimal and features closely relevant. File sharing is considered to provide more options in the future.

**Comment by MisteryMonster** [comment]
I think it's just really HTTP file server should do,  not really static website hosting (no cache needed, domain mapping thing etc, please tell me what's is your concern! ), is more over a request and link file in HTTP file server. Browser can natively render HTML just like playing videos, and you have already done with subtitle supported!

**Comment by MisteryMonster** [comment]
I get the idea and you are right. How about only in guest mode? Everything Guest could access (or permanent sharing without password) are statics path and without auth ( because it's public ) . BTW the sharing link seem have a bug that never expire.
