### ISSUE TITLE
打开txt文本的时候，里边的中文乱码，请修复

### ISSUE THREAD

**Issue by vip123456789** [machengim/oasis#4]
1、打开txt文本的时候，里边的中文乱码，请修复~
2、软件很好用，希望能增加上传功能，谢谢！
3、希望有其他交流的途径，比如QQ群等！

**Comment by machengim** [comment]
1. 会在近期修复
2. 谢谢，上传功能正在开发中
3. 基本不用QQ，如有问题可以提issue，也能方便有类似问题的人

**Comment by machengim** [comment]
文件编码问题已在0.2版中修复，请下载新的release使用。
