### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by vip123456789** [machengim/oasis#8]
1、对于ipv6的支持和https的支持，作者如果觉得有难度，可以采用caddy/nginx这类服务器反代oasis的方式轻松解决。
2、视频播放页面，文件列表窗口高度希望可调，或者可以和视频窗口采用一样的高度，这样界面会好看一些。
3、播放音乐的时候切换目录或者文件夹音乐会中断，希望可以将音乐播放器采用一个独立的组件，切换页面不影响音乐播放，就像网易云音乐那样的。

**Comment by machengim** [comment]
HTTPS 在计划中。理论上现在设置好配置文件也能使用ipv6，但是我没有条件测试，不知道具体是什么结果。播放器组件独立的事情我也想过，不过改动太大，等后面有时间再看。
